In [54]:
import pandas as pd

df = pd.read_csv("x://VScode//jupyter_lab//Pandas//globalAirQuality.csv")

In [55]:
#access columns
df["aqi"]
df[["city","aqi"]] #case senestive values 
# to access 2 or more values at once this is how we can do this 
#

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [57]:
# access indivisual cells
df.loc[0,"aqi"]

np.int64(108)

In [58]:
# access rows
df.loc[2]
df.loc[0:2] # start idx : end idx

df.iloc[2]
df.iloc[0:2] # start idx : end idx

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [59]:
df.loc[0:3,["city","aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84
3  New York  158

In [60]:
df.iloc[0:3,2]

0    New York
1    New York
2    New York
Name: city, dtype: object

In [62]:
df.iloc[0:3,5]

0    50.295
1    32.083
2    42.250
Name: pm25, dtype: float64

In [63]:
df.iloc[0:3, 0:7]

,timestamp,country,city,latitude,longitude,pm25,pm10
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553

In [64]:
# cell

df.at[0, "city"]

'New York'

In [68]:
df.iat[0,2]

'New York'

In [88]:
cities = df["city"]
cities[0] = "New York" # working on original data
df

C:\Users\Rajat Bhardwaj\AppData\Local\Temp\ipykernel_5256\1056323918.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cities[0] = "New York" # working on original data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [90]:
cities = df["city"].copy() # working on a copy data original data does not get affected
cities[0] = "New York"

In [92]:
# Filtering data

df[df["aqi"] > 100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [104]:
df[(df["aqi"] > 100) & (df["temperature"] > 30)][["city","aqi","temperature"]]

           city  aqi  temperature
6      New York  155       36.729
7      New York  115       37.891
14     New York  121       34.481
17     New York  127       36.193
25     New York  113       31.289
...         ...  ...          ...
17947    Zurich  107       32.584
17950    Zurich  140       36.885
17975    Zurich  111       30.761
17976    Zurich  146       30.909
17991    Zurich  104       32.556

[2384 rows x 3 columns]