In [76]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import accuracy_score
import numpy as np

In [62]:
house_price_data = pd.read_csv("X:\\Artificial Intelligence Course\\Supervised Learning\\Linear Regression\\HousePricePrediction.csv")
house_price_data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [63]:
house_price_data.drop(['Id'],axis=1,inplace=True)
house_price_data = house_price_data.dropna(subset=["SalePrice"])

In [64]:
categorical_cols = ["MSZoning", "LotConfig", "BldgType", "Exterior1st"]
house_price_data = pd.get_dummies(house_price_data, columns=categorical_cols, drop_first=False, dtype=int)

In [65]:
house_price_data = house_price_data.dropna()
house_price_data.head(10)

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_C (all),MSZoning_FV,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,20,9600,8,1976,1976,0.0,1262.0,181500.0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,60,11250,5,2001,2002,0.0,920.0,223500.0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,70,9550,5,1915,1970,0.0,756.0,140000.0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,60,14260,5,2000,2000,0.0,1145.0,250000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,50,14115,5,1993,1995,0.0,796.0,143000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,20,10084,5,2004,2005,0.0,1686.0,307000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,60,10382,6,1973,1973,32.0,1107.0,200000.0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,50,6120,5,1931,1950,0.0,952.0,129900.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,190,7420,6,1939,1950,0.0,991.0,118000.0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [66]:
house_price_data.isnull().sum().head()

MSSubClass      0
LotArea         0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
dtype: int64

In [67]:
X = house_price_data.drop(["SalePrice"],axis=1)
y = house_price_data["SalePrice"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.24, random_state=0)

In [68]:
X_train.head()
scaler = StandardScaler()

# Get list of numerical columns (excluding your encoded 0/1 columns)
num_cols = ["MSSubClass", "LotArea", "OverallCond", "YearBuilt", "YearRemodAdd", "BsmtFinSF2", "TotalBsmtSF"]

# Fit on training data and transform both sets
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [69]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [70]:
y_pred = model.predict(X_test)
y_series = pd.Series(y_pred)
print(f"Y predicted value: {y_series.sample(10)}")

Y predicted value: 244    191080.747556
315    149355.303506
86      89548.057920
43     278913.436726
32     221719.617973
79     221658.561981
234    217669.625399
88     226574.227909
92     180230.888257
10     219702.852017
dtype: float64

In [83]:
print(f"R2 score: {r2_score(y_test, y_pred):.4f}")
print(f"Mean absolute error: {mean_absolute_error(y_test, y_pred):.4f}")
print(f"Root mean squared error: {root_mean_squared_error(y_test, y_pred):.4f}")
print(f"Mean absolute percentage error :{mean_absolute_percentage_error(y_test,y_pred):.4f}")
# print(f"Accuracy Score: {accuracy_score(np.array([[0, 1], [1, 1]]), np.ones((2, 2))):.4f}")

R2 score: 0.4554
Mean absolute error: 33285.2541
Root mean squared error: 58868.8504
Mean absolute percentage error :0.2012